# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TourGallery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TourGallery

  target 'TourGalleryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TourGalleryUITests' do
    # Pods for testing
  end
  pod 'RxSwift'
  pod 'ReactorKit'
  pod 'RxAppState'
  pod 'SnapKit'
  pod 'Moya/RxSwift'
end
